### ISSUE TITLE
Unable to fetch eurovoc distribution

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-reference-data#103]
new-reference-data
Dette (eller et liknende problem) ble fikset i januar

`jsonPayload: {
logger_name: "no.fdk.referencedata.eu.eurovoc.EuroVocService"
message: "Unable to harvest eurovoc"
stack_hash: "c3273e5e"
stack_trace: "java.lang.Exception: Unable to fetch eurovoc distribution
	at n.f.r.e.e.EuroVocHarvester.harvest(EuroVocHarvester.java:41)
	at n.f.r.e.e.EuroVocService.harvestAndSave(EuroVocService.java:55)
	... 31 common frames omitted
Wrapped by: r.c.Exceptions$ReactiveException: java.lang.Exception: Unable to fetch eurovoc distribution
	at r.core.Exceptions.propagate(Exceptions.java:392)
	at r.c.p.BlockingIterable$SubscriberIterator.hasNext(BlockingIterable.java:169)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at n.f.r.e.e.EuroVocService.harvestAndSave(EuroVocService.java:56)
	at n.f.r.Scheduler.init(Scheduler.java:143)
	at j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
	at j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at j.l.reflect.Method.invoke(Method.java:568)
	at o.s.c.e.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344)
	at o.s.c.e.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229)
	at o.s.c.e.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166)
	at o.s.c.e.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at o.s.c.e.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at o.s.c.e.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at o.s.c.s.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at o.s.c.s.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at o.s.b.c.e.EventPublishingRunListener.ready(EventPublishingRunListener.java:114)
	at o.s.b.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:82)
	at java.util.ArrayList.forEach(ArrayList.java:1511)
	at o.s.b.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at o.s.b.Sprin...
"`

**Comment by valosnah** [comment]
Applikasjonen sliter fortsatt med eurovoc fra tid til annen
